name: Haskell CI

on:
  push:
    branches: [ 'main', 'ci' ]
  pull_request:
    branches: [ 'main' ]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os:  [ 'ubuntu-latest', 'macOS-latest', 'windows-latest' ]
        ghc: [ '8.8', '8.10', '9.0', '9.2', '9.4', '9.6' ]

    steps:
    - uses: actions/checkout@v3

    - uses: haskell/actions/setup@v2
      id: setup
      with:
        ghc-version: ${{ matrix.ghc }}
        cabal-version: latest
        cabal-update:  true

    - name: Cache (restore)
      uses: actions/cache/restore@v3
      id:   cache
      with:
        path: ${{ steps.setup.outputs.cabal-store }}
        key: build-${{ runner.os }}-ghc-${{ env.GHC_VERSION }}-cabal-${{ env.CABAL_VERSION }}-sha-${{ github.sha }}
          # Append commit SHA so that new cache is always written.
          # This is fine as long as we do not hit the total cache limit of 10GB.
        restore-keys: |
             build-${{ runner.os }}-ghc-${{ env.GHC_VERSION }}-cabal-${{ env.CABAL_VERSION }}-
             build-${{ runner.os }}-ghc-${{ env.GHC_VERSION }}-

    - name: Install dependencies
      run: |
        cabal update
        cabal build --only-dependencies --enable-tests --disable-benchmarks

    - name: Build
      run: cabal build --enable-tests --disable-benchmarks all

    - name: Run tests
      run: cabal test --test-show-details=streaming

    - name: Run doctest
      if: ${{ runner.os == 'Linux' }}
      run: |
        cabal install doctest --overwrite-policy=always
        cabal repl --build-depends=QuickCheck --with-ghc=doctest
